# Nixpacks configuration for Railway deployment
[phases.setup]
aptPkgs = ["python3", "python3-venv", "python3-pip"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "export PATH=/opt/venv/bin:$PATH",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python main.py"